### Numpy


In [1]:
import numpy as np

### 1D Arrays

In [2]:
a = np.array([10,20,30,50,60,0])


### Attributes of arrays
### dtype
### ndim
### size
### shape


In [4]:
a.dtype

dtype('int32')

In [5]:
a.shape

(6,)

In [6]:
a.ndim

1

In [7]:
a.size

6

In [8]:
a[0]

10

In [9]:
a[2]

30

### Another type of multi dimensional arrays

In [26]:
a_2d = np.array([[10,20,30,], [23,55,15]])

In [27]:
a_2d

array([[10, 20, 30],
       [23, 55, 15]])

In [28]:
a_2d.dtype


dtype('int32')

In [29]:
a_2d.shape

(2, 3)

In [30]:
a_2d.ndim

2

In [31]:
a_2d.size

6

In [32]:
a_2d[0]

array([10, 20, 30])

In [33]:
another_type_array = np.array([[[1,2,3,4]]])

In [34]:
another_type_array

array([[[1, 2, 3, 4]]])

In [35]:
another_type_array.ndim

3

In [36]:
a_2d[0][0]

10

In [37]:
a_2d[1][1]

55

In [40]:
a_2d = np.array([[10,20,30,], [23,55,15]], dtype = float)

In [41]:
a_2d

array([[10., 20., 30.],
       [23., 55., 15.]])

In [42]:
a_bigger = np.array([
[
[ 10, 20, 30, 40 ], [ 8 , 8 , 2 , 1 ], [ 1 , 1 , 1 , 2]
],    
[
[ 9 , 9 , 2 , 39 ], [ 1 , 2 , 3 , 3 ], [ 0, 0 , 3 , 2]
],
[
[ 12 , 33 , 22 ,1 ], [ 22 , 1 , 22 , 2 ], [ 0 , 2 , 3 , 1 ]
]   
] , dtype = float)      
   
    
    

In [43]:
a_bigger.shape

(3, 3, 4)

In [44]:
a_bigger.ndim

3

In [45]:
a_bigger.size


36

In [46]:
a_bigger[2][2][3]

1.0

In [47]:
a_bigger[2][2]

array([0., 2., 3., 1.])

### Filling arays

In [48]:
a_full = np.full(( 3 , 5 , 4 ), 7)

In [49]:
a_full

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

In [50]:
a_full.ndim

3

### Empty and Random

In [51]:
e  = np.empty((4,4))
e

array([[4.67296746e-307, 1.69121096e-306, 1.60221208e-306,
        8.34441742e-308],
       [1.78022342e-306, 6.23058028e-307, 9.79107872e-307,
        6.89807188e-307],
       [7.56594375e-307, 6.23060065e-307, 1.78021527e-306,
        8.34454050e-308],
       [1.11261027e-306, 1.15706896e-306, 1.33512173e-306,
        1.33504432e-306]])

In [52]:
b_random = np.random.random((2,2))
b_random

array([[0.73825189, 0.91679437],
       [0.63647163, 0.78479083]])

In [53]:
b_random.ndim

2

In [54]:
b_random.size

4

### Ranges

In [55]:
a_arange = np.arange(10 , 50, 5)

In [56]:
a_arange

array([10, 15, 20, 25, 30, 35, 40, 45])

### Linspace

In [58]:
b_linspace = np.linspace(0, 50 , 2)
b_linspace

array([ 0., 50.])

In [59]:
b_linspace.ndim

1

In [60]:
b_linspace.size

2

In [61]:
b_linspace1 = np.linspace(0,50,30)

In [62]:
b_linspace1

array([ 0.        ,  1.72413793,  3.44827586,  5.17241379,  6.89655172,
        8.62068966, 10.34482759, 12.06896552, 13.79310345, 15.51724138,
       17.24137931, 18.96551724, 20.68965517, 22.4137931 , 24.13793103,
       25.86206897, 27.5862069 , 29.31034483, 31.03448276, 32.75862069,
       34.48275862, 36.20689655, 37.93103448, 39.65517241, 41.37931034,
       43.10344828, 44.82758621, 46.55172414, 48.27586207, 50.        ])

In [63]:
b_linspace1.size

30

In [64]:
b_linspace2 = np.linspace(0,50,25, dtype=int)
b_linspace2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 50])

### Math functions

In [65]:
np.exp(a)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 5.18470553e+21,
       1.14200739e+26, 1.00000000e+00])

In [66]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162, -0.26237485, -0.30481062,
        0.        ])

In [67]:
np.cos(a)

array([-0.83907153,  0.40808206,  0.15425145,  0.96496603, -0.95241298,
        1.        ])

In [68]:
np.tan(a)

array([ 0.64836083,  2.23716094, -6.4053312 , -0.27190061,  0.32004039,
        0.        ])

In [69]:
np.log(a)

C:\Users\surya\AppData\Local\Temp/ipykernel_8156/176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([2.30258509, 2.99573227, 3.40119738, 3.91202301, 4.09434456,
             -inf])

In [70]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 7.07106781, 7.74596669,
       0.        ])

### Aggregate functions

In [72]:
a.sum()

170

In [73]:
a.min()

0

In [74]:
a.max()

60

In [75]:
a.mean()

28.333333333333332

In [76]:
np.median(a)

25.0

In [77]:
np.std(a)

21.147629234082533

In [78]:
np.median(b_linspace2)

25.0

In [79]:
np.sum(b_linspace2)

614

In [80]:
np.sqrt(b_linspace2)

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712,
       3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069,
       4.47213595, 4.69041576, 5.        , 5.19615242, 5.38516481,
       5.56776436, 5.74456265, 5.91607978, 6.08276253, 6.244998  ,
       6.40312424, 6.55743852, 6.70820393, 6.8556546 , 7.07106781])

In [81]:
np.std(b_linspace2)

14.924020905908701

In [ ]:
np.cos(b_linspace2)